### ISSUE TITLE
Support a `--token` flag

### ISSUE THREAD

**Issue by yuvalavra** [cyberark/kubeletctl#15]
Adding a `--token` flag would improve usability, at least for me. The command would then look something like:
```bash
$ kubeletctl --token=<token> --server=<addr> <command>
```

Using a token is probably also possible if you create an kubeconfig file and then use the `--config` flag, but I'd rather not do that.

**Comment by g3rzi** [comment]
I added support in `--token` and `--token-file` flags, I tested and it worked fine from my end.  

I published new version 1.8:
https://github.com/cyberark/kubeletctl/releases/tag/v1.8 

Thanks for the suggestion :)

**Comment by yuvalavra** [comment]
Works on my side as well, thank you
