### ISSUE TITLE
Support the Checkpoint API

### ISSUE THREAD

**Issue by christophetd** [cyberark/kubeletctl#23]
K8s 1.25 introduced the Checkpoint API https://betterprogramming.pub/backup-and-restore-of-containers-with-kubernetes-checkpointing-api-e310cf29cd4a. It would be great to have support in kubeletctl

**Comment by g3rzi** [comment]
Great, thanks for sharing, we will add it and update once done :)

**Comment by g3rzi** [comment]
Hi @christophetd 
We added support to the `/checkpoint` API.

**Comment by christophetd** [comment]
Great to hear, thanks!
