### ISSUE TITLE
Adding ARM support

### ISSUE THREAD

**Issue by frankvoelker** [cyberark/kubeletctl#39]
Add support for Linux ARM64

**Comment by g3rzi** [comment]
We added last week #38 
Did you try it? 

It's not part of the release yet but you can use the new code in the [Makefile](https://github.com/cyberark/kubeletctl/blob/master/Makefile).

**Comment by frankvoelker** [comment]
I see Darwin/ARM support (Mac) but no Linux. Or am I looking at the wrong place?

**Comment by g3rzi** [comment]
Sorry, my mistake. We will check it.

**Comment by g3rzi** [comment]
We fixed it in #42 .
We will add the ARM binaries in the next release.

**Comment by g3rzi** [comment]
You can check the new release:
https://github.com/cyberark/kubeletctl/releases/tag/v1.12
