### ISSUE TITLE
/metrics/resources/v1alpha1 endpoint going away in 1.18

### ISSUE THREAD

**Issue by trungng92** [cyberark/kubeletctl#9]
In version 1.18, the /metrics/resources/v1alpha1 endpoint will be going away.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md

> resource metrics endpoint /metrics/resource/v1alpha1 as well as all metrics under this endpoint have been deprecated. Please convert to the following metrics emitted by endpoint /metrics/resource: - scrape_error --> scrape_error - node_cpu_usage_seconds_total --> node_cpu_usage_seconds - node_memory_working_set_bytes --> node_memory_working_set_bytes - container_cpu_usage_seconds_total --> container_cpu_usage_seconds - container_memory_working_set_bytes --> container_memory_working_set_bytes - scrape_error --> scrape_error (#86282, @RainbowMango) [SIG Node]

**Comment by RainbowMango** [comment]
To be precise, the `/metrics/resources/v1alpha1` endpoint still available in Kubernetes 1.18.

**Comment by g3rzi** [comment]
Cool, thanks for the update!
I think I will leave this option for users that use older versions but send message that it doesn't support from k8s > 1.18

**Comment by 45Shirley** [comment]
🔥

**Comment by g3rzi** [comment]
The API is dynamic so no need to add an error.
Dynamic means that you can run anything after the `resource`.  
I updated  in the comments that it has been deprecated.
